### ISSUE TITLE
Non-ASCII characters and faulty import

### ISSUE THREAD

**Issue by bgbrink** [koszullab/HiC-Box#3]
In the current version the tool can't be launched. There are two reasons.

1. The script `pyramid_sparse.py` contains non ASCII characters, namely this recuring line:
`p = ProgressBar('blue', width=20, block='▣', empty='□')`
All of these lines are commented out anyway, so deleting them fixes the problem.

2. The script `main.py` imports weave from scipy. However, weave became its own project, so it needs to imported directly, otherwise it can't be found.

**Comment by baudrly** [comment]
Indeed. Thanks! Should be fixed now.
