### ISSUE TITLE
ValueError during alignment

### ISSUE THREAD

**Issue by bgbrink** [koszullab/HiC-Box#4]
when I run the HiC-Box alignment, I receive the following error:

```
[...]
start computing biases...
data exist. loading...
done
data collect_done
 numpy size shape =  (0,)
 numpy gc shape =  (0,)
 np vect size shape =  (95581,)
 np vect gc shape =  (95581,)
Traceback (most recent call last):
  File "main.py", line 278, in OnAlign
    ncpu=self.ncpu)
  File "/Python/HiC-Box/analysis_main.py", line 110, in analyze
    hic_bank.gc_size_bias()
  File "/Python/HiC-Box/hic_exp.py", line 165, in gc_size_bias
    mat_gc, mat_size,steps_gc,steps_length =  hic_analysis.gc_size_bias(self.folder_analysis,self.dict_fragments, self.fragments_contacts_file)
  File "/Python/HiC-Box/hic_analysis.py", line 203, in gc_size_bias
    size_min = numpy_size.min()
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation minimum which has no identity
```

Could you help me figure out what went wrong here?

**Comment by baudrly** [comment]
```
 numpy size shape =  (0,)
 numpy gc shape =  (0,)
```

This usually happens when there are no contacts to make a matrix from. Please check whether your reads mapped correctly on the reference genome; failing that, try to delete the whole output folder and restart with a fresh alignment. If you still encounter issues let me know.

**Comment by bgbrink** [comment]
Hmm I see. Maybe I should elaborate a bit more.
When I use the HiC-Box to create the alignment from scratch, there seems to be some kind of memory leak. It fills up my computer's memory (16GB RAM + 32GB SWAP) and then crashes. Thus, I ran bowtie2 directly using the same parameters (which only uses about 3GB of memory btw) and placed the resulting sam file in .../tmp0/0.sam. The HiC-Box recongnizes the file and continues with the analysis, however then fails as described above. 
Maybe there need to be additional steps in order to call bowtie separately?

**Comment by baudrly** [comment]
Probably something needs to be optimized in the pipeline. Does the crash happen after it says 'here we go' by any chance?

**Comment by bgbrink** [comment]
The memory crash? Yes that happened after 'here we go'.

**Comment by baudrly** [comment]
It seems the memory crash occurs while creating a 'tag' dictionary for the reads. While I'm looking into this, you may go around the issue by trimming your reads and removing PCR duplicates yourself. An example of a script that does this is found [here](https://github.com/koszullab/DADE/blob/master/pcr_duplicate_Hiseq.pl) (adapt to fit your needs). Then, before you launch the box on these new reads, click on 'options' and set 'tag length' to 0. This causes the snippet responsible for the crash to be ignored by the pipeline.

**Comment by bgbrink** [comment]
Thanks, that worked!

**Comment by baudrly** [comment]
Good! I'm going to close this for now, as I think that approach (cleaning your reads prior to the pipeline instead of doing it on the fly every time) is more sound anyway, especially with large sets of reads. I added a troubleshooting section to explain what to do.
