### ISSUE TITLE
Unable to run main.py + suggestions

### ISSUE THREAD

**Issue by JuanmaMedina** [koszullab/HiC-Box#5]
Good afternoon!

I am trying to explore and use HiC-box to build a contact map from a metagenomics sample from which we have both a shotgun sequencing library and a HiC library availables, and hopefully extend its analysis with GRAAL. However, I am running some trouble with the first steps of the installation, more specifically, running main.py script.

When I call `python main.py`,
I get this error: `Unable to access the X Display, is $DISPLAY set properly?`

I have done some research and I think this is an error related to `wxpython `module, but I have tried to install several versions of it and I have not been able to solve it. Could you point me out how to proceed here? Any idea is very welcome!

Apart from this, I have a couple of suggestions to add in the initial documentation:

1. Specify that this requires a Python2.7 environment (maybe a bit obvious, but several users already rely on Python3)

2. Add `cython` (as it is required by `mirnylib`) and `wxpython` to the python dependencies required by HiC-Box, as it is required by `wx` module (here is where I suspect I am having my issues). Both of them can be installed easiliy through `conda`

` conda install -c anaconda wxpython cython`

Nothing else, I hope to hear from you soon, and I will be very happy to provide you with more feedback if this keeps working! Thanks for the development, the tool looks promising!

Best,
Juanma

**Comment by baudrly** [comment]
Hello,

>I have done some research and I think this is an error related to wxpython module, but I have tried to install several versions of it and I have not been able to solve it. Could you point me out how to proceed here? Any idea is very welcome!

What version of wxpython are you using? From experience both 2.8 and 3.0 work fine. This error also shows up if you try to run the box from the command line with no X display available. Just for clarification, this is meant to be a graphical interface. If you want to run a Hi-C pipeline from the command line only you can use [DADE](https://github.com/koszullab/DADE), [my custom pipeline](https://github.com/baudrly/yahcp) or just follow the steps in [this tutorial](https://github.com/axelcournac/3C_tutorial).

>Specify that this requires a Python2.7 environment (maybe a bit obvious, but several users already rely on Python3)
>Add cython (as it is required by mirnylib) and wxpython to the python dependencies required by HiC-Box, as it is required by wx module (here is where I suspect I am having my issues). Both of them can be installed easiliy through conda

Good point, the box was written a couple years ago but python 2 deprecation is coming up soon. Also thanks for the suggestions and feedback! I will add this info to the readme.

**Comment by JuanmaMedina** [comment]
Hello Lyam. Thanks for your answer!

The graphical interface specification explains my problem then, and `wxpython `was not an issue. Thank you very much for the links offered, but given that I am dealing with a metagenomics sample, I am currently working around the `meta3Cbox` pipeline. I will gladly add future potential improvements in its corresponding issues section, which I think I can update a bit!

Best,
Juanma
